<div class="mh-form-view">
    <div class="mh-form-head"><div><span class="mh-kicker">Historical visit</span><h4>{{ $visit->consultation_id }}</h4><p>{{ $visit->consultation_date->format('F d, Y h:i A') }} · {{ str_replace('_', ' ', ucwords($visit->consultation_type, '_')) }}</p></div><button class="btn-secondary" type="button" onclick="loadMedicalHistory()">Back to Medical History</button></div>
    <section class="mh-form-section"><h5>Visit Summary</h5><div class="mh-detail-grid"><div><label>Patient</label><p>{{ $visit->patient->first_name }} {{ $visit->patient->last_name }}</p></div><div><label>Attending provider</label><p>{{ $visit->provider->name ?? '---' }}</p></div><div><label>Reason for visit</label><p>{{ $visit->reason_for_visit ?: '---' }}</p></div><div><label>Chief complaint</label><p>{{ $visit->chief_complaint ?: '---' }}</p></div></div></section>
    @if($visit->previousConsultation || $visit->ncdAssessment)<section class="mh-form-section mh-previous-record"><h5>Previous Record</h5><div class="mh-detail-grid"><div><label>Previous assessment / visit</label><p>@if($visit->previousConsultation){{ $visit->previousConsultation->consultation_id }} · {{ $visit->previousConsultation->consultation_date->format('M d, Y') }}@else Initial NCD Assessment · {{ $visit->ncdAssessment->assessment_date ?: 'Undated' }}@endif</p></div><div><label>Previous important findings</label><p>@if($visit->previousConsultation){{ $visit->previousConsultation->assessment }}@else BP: {{ $visit->ncdAssessment->bp_b ?: '---' }} · BMI: {{ $visit->ncdAssessment->bmi ?: '---' }}@endif</p></div></div></section>@endif
    <section class="mh-form-section"><h5>Current Symptoms</h5><div class="mh-detail-grid"><div><label>Chief complaint</label><p>{{ $visit->chief_complaint ?: '---' }}</p></div><div><label>Current findings</label><p>{{ $visit->details['current_findings'] ?? '---' }}</p></div><div><label>Changes since last visit</label><p>{{ $visit->details['changes_since_last_visit'] ?? '---' }}</p></div></div></section>
    <section class="mh-form-section"><h5>Current Vital Signs</h5><div class="mh-vital-list mh-vital-list-large"><div><label>Blood pressure</label><strong>{{ $visit->blood_pressure ?: '---' }}</strong></div><div><label>Temperature</label><strong>{{ $visit->temperature ?: '---' }}</strong></div><div><label>Pulse</label><strong>{{ $visit->pulse_rate ?: '---' }}</strong></div><div><label>Respiratory rate</label><strong>{{ $visit->respiratory_rate ?: '---' }}</strong></div><div><label>SpO2</label><strong>{{ $visit->oxygen_saturation ?: '---' }}</strong></div><div><label>Weight / Height</label><strong>{{ $visit->weight ?: '---' }} / {{ $visit->height ?: '---' }}</strong></div><div><label>BMI</label><strong>{{ $visit->bmi ?: '---' }}</strong></div></div></section>
    @if(($visit->consultation_type === 'consultation' && $visit->reason_for_visit === 'NCD Follow-up') || $visit->consultation_type === 'ncd_follow_up')<section class="mh-form-section"><h5>Disease Monitoring</h5><div class="mh-detail-grid"><div><label>Hypertension</label><p>{{ $visit->details['hypertension_status'] ?? 'Not recorded' }}</p></div><div><label>Diabetes</label><p>{{ $visit->details['diabetes_status'] ?? 'Not recorded' }} · Blood sugar: {{ $visit->details['current_blood_sugar'] ?? '---' }}</p></div><div><label>Medication compliance</label><p>{{ $visit->details['medication_compliance'] ?? 'Not recorded' }}</p></div><div><label>Medication action</label><p>{{ $visit->details['medication_action'] ?? 'Not recorded' }}</p></div></div></section>@endif
    <section class="mh-form-section"><h5>Assessment</h5><div class="mh-detail-grid"><div><label>Diagnosis / assessment</label><p>{{ $visit->assessment ?: '---' }}</p></div><div><label>Condition status</label><p>{{ $visit->details['condition_status'] ?? '---' }}</p></div><div><label>Clinical findings</label><p>{{ $visit->details['clinical_findings'] ?? '---' }}</p></div></div></section>
    <section class="mh-form-section"><h5>Plan / Management</h5><div class="mh-detail-grid"><div><label>Treatment</label><p>{{ $visit->treatment ?: '---' }}</p></div><div><label>Medicines</label><p>{{ $visit->medicines ?: '---' }}</p></div><div><label>Health advice</label><p>{{ $visit->details['health_advice'] ?? '---' }}</p></div><div><label>Laboratory / referral</label><p>{{ $visit->details['laboratory_request'] ?? '---' }}<br>{{ $visit->details['referral'] ?? '' }}</p></div><div><label>Next follow-up</label><p>{{ $visit->follow_up_date?->format('M d, Y') ?: '---' }}</p></div></div></section>
    <section class="mh-form-section"><h5>Notes</h5><p>{{ $visit->details['notes'] ?? '---' }}</p></section>
</div>